"""The manifest that lets vendored binaries leave git-LFS (MAST_provisioning#48).

Every git-LFS pointer already carries the `oid sha256` and `size` of the object it
stands for. So the record needed to *replace* LFS is the record LFS itself keeps,
and this manifest is derived from the pointers rather than written by anyone --
which is what makes retiring LFS mechanical instead of a transcription exercise,
and what keeps the two from disagreeing while both exist.

The content-addressed store on the relay already holds these bytes: measured
2026-09-17, every payload file is a blob there. So the manifest is the index into
a store that exists, not a plan for one.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path
from typing import Any

_OID = re.compile(rb"^oid sha256:([0-9a-f]{64})$", re.MULTILINE)
_SIZE = re.compile(rb"^size (\d+)$", re.MULTILINE)
#: server/providers/<module>/assets/... -- the per-provider layout.
_PROVIDER = re.compile(r"^server/providers/([^/]+)/assets/")
#: client/assets/... -- the bootstrap payload, which belongs to no provider.
_CLIENT = re.compile(r"^client/assets/")


def module_of(path: str) -> str | None:
    """Which provider owns an asset, for a drift report a person has to read."""
    m = _PROVIDER.match(path)
    if m:
        return m.group(1)
    return "client" if _CLIENT.match(path) else None


def _git(repo: Path, *args: str, stdin: bytes | None = None) -> bytes:
    return subprocess.run(["git", *args], cwd=repo, input=stdin, capture_output=True, check=True).stdout


def discover_lfs_paths(repo: Path) -> set[str]:
    try:
        out = _git(repo, "lfs", "ls-files", "-n")
    except (subprocess.CalledProcessError, FileNotFoundError):
        return set()
    return {line for line in out.decode("utf-8", "surrogateescape").splitlines() if line}


def _pointers(repo: Path, paths: list[str]) -> dict[str, bytes]:
    """Every pointer blob in ONE git call; see prov.tree_integrity for why."""
    if not paths:
        return {}
    req = "".join(f"HEAD:{p}\n" for p in paths).encode("utf-8", "surrogateescape")
    out = _git(repo, "cat-file", "--batch", stdin=req)
    blobs: dict[str, bytes] = {}
    pos = 0
    for path in paths:
        nl = out.index(b"\n", pos)
        header = out[pos:nl].split()
        if len(header) < 3:
            pos = nl + 1
            continue
        size = int(header[2])
        start = nl + 1
        blobs[path] = out[start : start + size]
        pos = start + size + 1
    return blobs


def build_manifest(repo: Path, *, lfs_paths: set[str] | None = None) -> dict[str, Any]:
    """Index of every LFS-held asset: path, sha256, size, owning module.

    No timestamp and no host. This file is committed and regenerated, so anything
    that changes when nothing changed would churn the diff and teach the reader to
    skip it -- the same reason the provenance generator is byte-stable.
    """
    repo = Path(repo)
    ordered = sorted(discover_lfs_paths(repo) if lfs_paths is None else lfs_paths)
    pointers = _pointers(repo, ordered)

    files = []
    for path in ordered:
        blob = pointers.get(path)
        if blob is None:
            continue
        oid, size = _OID.search(blob), _SIZE.search(blob)
        if not (oid and size):
            # Tracked as LFS but not a pointer in HEAD: nothing to record, and
            # guessing a hash here would put a wrong one in the index.
            continue
        files.append(
            {
                "path": path,
                "sha256": oid.group(1).decode(),
                "size": int(size.group(1)),
                "module": module_of(path),
            }
        )
    return {
        "_comment": (
            "Generated by prov.asset_manifest from the git-LFS pointers -- do not hand-edit. "
            "Each row is the path, sha256 and size the pointer already recorded, plus the "
            "provider that owns it. See MAST_provisioning#48."
        ),
        "files": files,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", type=Path, default=Path.cwd())
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args(argv)
    manifest = build_manifest(a.repo)
    a.out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    total = sum(f["size"] for f in manifest["files"])
    print(f"wrote {len(manifest['files'])} assets ({total / 2**30:.2f} GiB) to {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
