#!/usr/bin/env python3
"""Write the provenance for each vendor input beside the bytes it describes.

The canonical copies live on mast-ns-control under /Storage/mast-vendor/. Somebody
rebuilding the build host from that mirror has the bytes and may not have this
repo, so the answer to *where did this come from and how do I get it again* has to
travel with them (#194).

Generated, never hand-written: server/data/vendor-inputs.json already carries the
prose, and a second copy maintained by hand is a second copy that goes stale.

Deliberately carries no checksum. Every one of these files is already a blob in
the content-addressed store (#202) whose name IS its SHA-256, so a hash written
here would be a staler answer to a question already answered -- and verifying the
build host's cache against the store is what tools/vendor-verify.sh does.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = "<!-- Generated by tools/write-vendor-provenance.py from server/data/vendor-inputs.json. Do not edit. -->\n"


def render_entry(entry: dict) -> str:
    used_by = ", ".join(f"`{m}`" for m in entry["used_by"])
    return (
        f"{HEADER}\n"
        f"# {entry['name']}\n\n"
        f"- **Build host path:** `{entry['path']}`\n"
        f"- **Kind:** {entry['kind']}, about {entry['approx_bytes']:,} bytes\n"
        f"- **Used by:** {used_by}, via `{entry['build_reference']}`\n\n"
        f"## Why it is not in the repository\n\n{entry['why_not_in_repo']}\n\n"
        f"## Where it came from\n\n{entry['origin']}\n\n"
        f"## How to acquire it again\n\n{entry['reacquire']}\n"
    )


def provenance_path(out: Path, entry: dict) -> Path:
    """Where one entry's provenance goes, which depends on what the entry IS.

    This tree is rsynced INTO /Storage/mast-vendor/, over the bytes it describes,
    so the shape here is not cosmetic. A directory entry takes a PROVENANCE.md
    inside it; a FILE entry must not, because creating `full-frame.fits/` makes
    rsync replace the 90 MB file with a directory and every later sync of the real
    file then fails with a directory in the way. Done on 2026-09-17 and recovered
    from the content store, which still held the blob.
    """
    if entry["kind"] == "file":
        return out / (entry["name"] + ".PROVENANCE.md")
    d = out / entry["name"]
    d.mkdir(parents=True, exist_ok=True)
    return d / "PROVENANCE.md"


def render_index(entries: list[dict]) -> str:
    lines = [
        HEADER,
        "\n# Vendor inputs for the MAST provisioning build host\n\n",
        "The build-host inputs that are not in the MAST_provisioning repository and are hard\n",
        "to re-acquire: if the provisioning server were lost, this is the set that would have\n",
        "to be reconstructed by hand. Each directory below carries its own PROVENANCE.md.\n\n",
        "These copies are canonical. The build host holds a working cache so a build never\n",
        "depends on the WAN, and that cache is checked against the content store rather than\n",
        "trusted (MAST_provisioning#194).\n\n",
        "| Entry | Kind | Approx. bytes | Used by |\n| --- | --- | ---: | --- |\n",
    ]
    for e in entries:
        lines.append(f"| `{e['name']}` | {e['kind']} | {e['approx_bytes']:,} | {', '.join(e['used_by'])} |\n")
    return "".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--inputs", type=Path, required=True, help="server/data/vendor-inputs.json")
    ap.add_argument("--out", type=Path, required=True, help="directory to write the tree into")
    args = ap.parse_args()

    entries = json.loads(args.inputs.read_text(encoding="utf-8"))["inputs"]
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "PROVENANCE.md").write_text(render_index(entries), encoding="utf-8")
    for entry in entries:
        provenance_path(args.out, entry).write_text(render_entry(entry), encoding="utf-8")
    print(f"wrote provenance for {len(entries)} entries into {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
